# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallerys', '0002_remove_category_image_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cartegory',
            new_name='category',
        ),
    ]
