# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallerys', '0003_auto_20180928_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerys.Category'),
        ),
    ]
